[tool.flake8]
max-line-length = 120
ignore = "E203, E266, E501, W503"

[tool.poetry]
name = "fhr"
version = "0.3.0"
description = "This tool is used to validate and convert between different FHR header serializations"
authors = ["David Molik <david.molik@usda.gov>","Adam Wright <adam.wright@oicr.on.ca>"]
license = "USDA-ARS"
readme = "README.md"
packages = [{include = "fhr"}]
include = ["fhr/fhr_schema.json"]

[tool.poetry.dependencies]
python = "^3.9"
jsonschema = {version = "^4.21.1", extras = ["format"]}
pyyaml = "^6.0.1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.8.0"
types-pyyaml = "^6.0.12.12"
types-jsonschema = "^4.21.0.20240118"
isort = "^5.13.2"
black = [
    { version = "^26.3.1", python = ">=3.10" },
    { version = "24.2.0", python = "<3.10" },
]
ruff = "^0.2.1"
pytest = "^8.0.0"

[tool.poetry.scripts]
fhr-convert = "fhr.cli:convert_main"
fhr-validate = "fhr.cli:validate_main"
fhr-fasta-strip = "fhr.cli:fasta_strip_main"
fhr-fasta-combine = "fhr.cli:fasta_combine_main"
fhr-fasta-validate = "fhr.cli:fasta_validate_main"
fhr-gfa-strip = "fhr.cli:gfa_strip_main"
fhr-gfa-combine = "fhr.cli:gfa_combine_main"
fhr-gfa-validate = "fhr.cli:gfa_validate_main"



[build-system]
requires = ["poetry-core>=1.8,<3"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.black]
target-version = ["py39"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
